/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guimyexperience.view;
import guimyexperience.model.User;
import guimyexperience.model.BusinessOwner;
import javax.swing.*;
import java.net.HttpURLConnection;
import java.net.URL;
import org.json.JSONObject;
import java.nio.charset.StandardCharsets;
import java.io.OutputStream;
import guimyexperience.dto.CreateBusinessOwnerRequest;
/**
 *
 * @author maelfye
 */
public class BusinessCreation extends javax.swing.JFrame {
  private User user;
  private String password;
    

    public BusinessCreation(User user,String password) {
        this.user = user;
        this.password = password;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBuisnessName = new javax.swing.JLabel();
        txtBuisnessName = new javax.swing.JTextField();
        lblBuisnessAdress = new javax.swing.JLabel();
        txtBuisnessAdress = new javax.swing.JTextField();
        lblBuisnessdescritpion = new javax.swing.JLabel();
        txtBuisnessDescription = new javax.swing.JTextField();
        BSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBuisnessName.setText("Buisness Name ");

        lblBuisnessAdress.setText("Buisness Adress");

        lblBuisnessdescritpion.setText("Buisness description :");

        txtBuisnessDescription.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtBuisnessDescription.setAlignmentX(0.0F);
        txtBuisnessDescription.setAlignmentY(0.0F);
        txtBuisnessDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuisnessDescriptionActionPerformed(evt);
            }
        });

        BSubmit.setText("Submit");
        BSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(BSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(txtBuisnessDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBuisnessdescritpion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBuisnessAdress)
                            .addComponent(lblBuisnessName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBuisnessName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtBuisnessAdress))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuisnessName)
                    .addComponent(txtBuisnessName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuisnessAdress)
                    .addComponent(txtBuisnessAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBuisnessdescritpion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BSubmit))
                    .addComponent(txtBuisnessDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuisnessDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuisnessDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuisnessDescriptionActionPerformed

    private void BSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSubmitActionPerformed
    
    //Collect business form data
    String businessName = txtBuisnessName.getText();
    String businessAddress = txtBuisnessAdress.getText();
    String businessDescription = txtBuisnessDescription.getText();

    //Build the BusinessOwner from the base user
    BusinessOwner bo = new BusinessOwner(
        user,
        businessName,
        businessAddress,
        businessDescription,
        null 
    );

    //Create the DTO and fill it
    CreateBusinessOwnerRequest requestDTO = new CreateBusinessOwnerRequest();
    requestDTO.setBusinessOwner(bo);
    requestDTO.setPassword(password); 

    try {
        // Build request JSON 
        JSONObject businessJson = new JSONObject();
        businessJson.put("firstName", bo.getFirstName());
        businessJson.put("lastName", bo.getLastName());
        businessJson.put("phone", bo.getPhone());
        businessJson.put("email", bo.getEmail());
        businessJson.put("address", bo.getAddress());
        businessJson.put("userType", "BusinessOwner");
        businessJson.put("businessName", bo.getBusinessName());
        businessJson.put("businessAddress", bo.getBusinessAddress());
        businessJson.put("businessDescription", bo.getBusinessDescription());

        JSONObject requestJson = new JSONObject();
        requestJson.put("businessOwner", businessJson);
        requestJson.put("password", requestDTO.getPassword());

        //Send the POST request
        String apiUrl = "http://localhost:8080/api/users/business-owners"; 
        URL url = new URL(apiUrl);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();

        conn.setRequestMethod("POST");
        conn.setRequestProperty("Content-Type", "application/json");
        conn.setDoOutput(true);

        try (OutputStream os = conn.getOutputStream()) {
            byte[] input = requestJson.toString().getBytes(StandardCharsets.UTF_8);
            os.write(input, 0, input.length);
        }

        int responseCode = conn.getResponseCode();

        if (responseCode == 201) {
            JOptionPane.showMessageDialog(this, "Business account created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            new Connexion().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Failed to create business account. Code: " + responseCode, "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error sending business data to server.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSubmit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBuisnessAdress;
    private javax.swing.JLabel lblBuisnessName;
    private javax.swing.JLabel lblBuisnessdescritpion;
    private javax.swing.JTextField txtBuisnessAdress;
    private javax.swing.JTextField txtBuisnessDescription;
    private javax.swing.JTextField txtBuisnessName;
    // End of variables declaration//GEN-END:variables
}
